// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"; // 1. 부품 가져오기 (Import)

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* 2. 길었던 코드 대신 단 한 줄로 끝! */}
        <Navbar />

        <main className="p-4">
          {children}
        </main>
        
        <footer className="p-4 bg-gray-100 text-center text-xs text-gray-500 mt-10">
          © 2025 My First Next.js App
        </footer>
      </body>
    </html>
  );
}